name: Build and deploy Node.js app to Azure Web App - Ancillares2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build  # Asumiendo que 'build' crea el directorio 'dist'
      - uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-app
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'Ancillares2'
          slot-name: 'production'  # Puedes usar un slot de staging si lo necesitas
          package: .